# add this on application-test.properties code
spring.datasource.url=jdbc:h2:mem:vending-app;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.main.banner-mode=off
spring.flyway.enabled=false
app.cors.allowed-origins=https://spa.example.test
